In [1]:
import pandas as pd
from openpyxl import Workbook
from openpyxl.styles import Font, Color
import os

# Caminhos dos arquivos CSV

In [2]:
original_path = "/media/jczars/4C22F02A22F01B22/Pollen-Classification-CBAM/results/phase1/AT_densenet+cbam_exp/0_DenseNet201_reports_consolidated/class_report_test_0_DenseNet201.csv"
equatorial_path = "/media/jczars/4C22F02A22F01B22/Pollen-Classification-CBAM/results/phase3/CPD1_TEST_VIEW/0_DenseNet201_EQUATORIAL_consolidated/class_report_test_0_DenseNet201.csv"
polar_path = "/media/jczars/4C22F02A22F01B22/Pollen-Classification-CBAM/results/phase3/CPD1_TEST_VIEW/0_DenseNet201_POLAR_consolidated/class_report_test_0_DenseNet201.csv"

# Read csv

In [3]:
original_df = pd.read_csv(original_path, sep=";", decimal=",")
original_df

    Unnamed: 0     Classes  Accuracy  Precision  Recall  F1-Score  Support
0            0  asphodelus     1.000      1.000   1.000     1.000       34
1            1  calicotome     0.993      0.980   0.993     0.986      298
2            2    castanea     1.000      1.000   1.000     1.000      218
3            3   ceratonia     0.940      0.931   0.940     0.935      100
4            4      ebenus     1.000      1.000   1.000     1.000       22
5            5       erica     1.000      0.989   1.000     0.994      181
6            6  eucalyptus     0.971      0.971   0.971     0.971      170
7            7      ferula     0.988      1.000   0.988     0.994       83
8            8      myrtus     1.000      0.997   1.000     0.998      786
9            9        olea     0.994      0.994   0.994     0.994      790
10          10    origanum     0.971      0.982   0.971     0.976      171
11          11      oxalis     0.993      0.993   0.993     0.993      139
12          12       pinus     1.000      1.000   1.000     1.000       29
13          13    pistacia     1.000      1.000   1.000     1.000       34
14          14      salvia     0.989      0.994   0.989     0.991      178
15          15    satureja     0.944      1.000   0.944     0.971       71
16          16     sinapis     0.990      0.990   0.990     0.990      197
17          17     thymbra     0.993      0.993   0.993     0.993      146
18          18     urginea     1.000      1.000   1.000     1.000      109
19          19       vitis     0.985      0.989   0.985     0.987      269

In [4]:
equatorial_df = pd.read_csv(equatorial_path, sep=";", decimal=",")
equatorial_df

    Unnamed: 0     Classes  Accuracy  Precision  Recall  F1-Score  Support
0            0  asphodelus     1.000      1.000   1.000     1.000      5.0
1            1  calicotome     0.909      0.769   0.909     0.833     11.0
2            2    castanea     1.000      1.000   1.000     1.000    218.0
3            3   ceratonia     0.948      0.938   0.948     0.943     96.0
4            4      ebenus     1.000      1.000   1.000     1.000     22.0
5            5       erica     1.000      0.667   1.000     0.800      2.0
6            6  eucalyptus     1.000      0.750   1.000     0.857      6.0
7            7      ferula     1.000      1.000   1.000     1.000     67.0
8            8      myrtus     1.000      1.000   1.000     1.000      2.0
9            9        olea     0.996      0.993   0.996     0.994    767.0
10          10    origanum     0.963      0.990   0.963     0.976    108.0
11          11      oxalis     1.000      1.000   1.000     1.000     14.0
12          12       pinus     0.000      0.000   0.000     0.000      0.0
13          13    pistacia     1.000      1.000   1.000     1.000     33.0
14          14      salvia     0.981      1.000   0.981     0.990    104.0
15          15    satureja     0.950      1.000   0.950     0.974     40.0
16          16     sinapis     0.990      0.990   0.990     0.990    196.0
17          17     thymbra     1.000      1.000   1.000     1.000     62.0
18          18     urginea     1.000      1.000   1.000     1.000    109.0
19          19       vitis     0.988      0.992   0.988     0.990    248.0

In [5]:
polar_df = pd.read_csv(polar_path, sep=";", decimal=",")
polar_df

    Unnamed: 0     Classes  Accuracy  Precision  Recall  F1-Score  Support
0            0  asphodelus     1.000      1.000   1.000     1.000     29.0
1            1  calicotome     0.997      0.990   0.997     0.993    287.0
2            2    castanea     0.000      0.000   0.000     0.000      0.0
3            3   ceratonia     0.750      0.750   0.750     0.750      4.0
4            4      ebenus     0.000      0.000   0.000     0.000      0.0
5            5       erica     1.000      0.994   1.000     0.997    179.0
6            6  eucalyptus     0.970      0.981   0.970     0.975    164.0
7            7      ferula     0.938      1.000   0.938     0.968     16.0
8            8      myrtus     1.000      0.997   1.000     0.998    784.0
9            9        olea     0.913      1.000   0.913     0.955     23.0
10          10    origanum     0.984      0.969   0.984     0.976     63.0
11          11      oxalis     0.992      0.992   0.992     0.992    125.0
12          12       pinus     1.000      1.000   1.000     1.000     29.0
13          13    pistacia     1.000      1.000   1.000     1.000      1.0
14          14      salvia     1.000      0.987   1.000     0.993     74.0
15          15    satureja     0.935      1.000   0.935     0.966     31.0
16          16     sinapis     1.000      1.000   1.000     1.000      1.0
17          17     thymbra     0.988      0.988   0.988     0.988     84.0
18          18     urginea     0.000      0.000   0.000     0.000      0.0
19          19       vitis     0.952      0.952   0.952     0.952     21.0

# Diretório de saída

In [6]:
output_dir = "/media/jczars/4C22F02A22F01B22/Pollen-Classification-CBAM/discussion"
excel_path = f"{output_dir}/Comparison_Metrics.xlsx"

# criar a planilha

In [7]:
# Criar um arquivo Excel vazio com uma aba padrão
excel_path = os.path.join(output_dir, "Comparison_Metrics_b1.xlsx")
workbook = Workbook()
workbook.save(excel_path)
print(f"Arquivo Excel criado com sucesso: {excel_path}")

Arquivo Excel criado com sucesso: /media/jczars/4C22F02A22F01B22/Pollen-Classification-CBAM/discussion/Comparison_Metrics_b1.xlsx

In [8]:
# Preencher a planilha com as comparações
with pd.ExcelWriter(excel_path, engine="openpyxl", mode="a", if_sheet_exists="replace") as writer:
    original_df.to_excel(writer, sheet_name="Original", index=False)
    equatorial_df.to_excel(writer, sheet_name="Equatorial", index=False)
    polar_df.to_excel(writer, sheet_name="Polar", index=False)

In [ ]:
# Função para carregar e filtrar uma aba da planilha
def load_and_filter_sheet(file_path, sheet_name):
    # Carregar a aba específica
    df = pd.read_excel(file_path, sheet_name=sheet_name)
    
    # Filtrar classes com Support > 0
    df_filtered = df[df['Support'] > 0]
    
    # Converter colunas numéricas para float (se necessário)
    numeric_columns = ['Accuracy', 'Precision', 'Recall', 'F1-Score', 'Support']
    df_filtered[numeric_columns] = df_filtered[numeric_columns].astype(float)
    
    return df_filtered

In [ ]:
# Função para comparar duas tabelas
def compare_tables(df_orig, df_comp):
    # Garantir que ambas as tabelas tenham as mesmas classes
    common_classes = df_orig["Classes"].isin(df_comp["Classes"])
    df_orig_filtered = df_orig[common_classes]
    df_comp_filtered = df_comp[df_comp["Classes"].isin(df_orig["Classes"])]

    if df_orig_filtered.empty or df_comp_filtered.empty:
        print("Nenhuma classe em comum encontrada entre as tabelas.")
        return pd.DataFrame()

    # Criar um DataFrame vazio para armazenar os resultados da comparação
    comparison_df = pd.DataFrame()
    comparison_df["Classes"] = df_orig_filtered["Classes"]
    
    # Definir as métricas a serem comparadas
    metrics = ['Accuracy', 'Precision', 'Recall', 'F1-Score']
    
    for metric in metrics:
        orig_metric = f"{metric}_Orig"
        comp_metric = f"{metric}_Comp"
        
        # Adicionar colunas ao DataFrame de comparação
        comparison_df[orig_metric] = df_orig_filtered[metric].values
        comparison_df[comp_metric] = df_comp_filtered[metric].values
        
        # Identificar casos iguais, superiores ou inferiores
        comparison_df[f"{metric}_Comparison"] = "Equal"
        comparison_df.loc[
            comparison_df[orig_metric] < comparison_df[comp_metric], f"{metric}_Comparison"
        ] = "Better"
        comparison_df.loc[
            comparison_df[orig_metric] > comparison_df[comp_metric], f"{metric}_Comparison"
        ] = "Worse"
    
    return comparison_df

In [ ]:
# Função para comparar duas tabelas e formatar
def compare_and_format(df_orig, df_comp, sheet_name, output_path):
    # Garantir que ambas as tabelas tenham as mesmas classes
    common_classes = df_orig["Classes"].isin(df_comp["Classes"])
    df_orig_filtered = df_orig[common_classes]
    df_comp_filtered = df_comp[df_comp["Classes"].isin(df_orig["Classes"])]

    if df_orig_filtered.empty or df_comp_filtered.empty:
        print(f"Nenhuma classe em comum encontrada para {sheet_name}.")
        return

    # Criar um DataFrame vazio para armazenar os resultados
    comparison_df = pd.DataFrame()
    comparison_df["Classes"] = df_orig_filtered["Classes"]

    # Definir as métricas a serem comparadas
    metrics = ['Accuracy', 'Precision', 'Recall', 'F1-Score']

    for metric in metrics:
        orig_metric = f"{metric}_Orig"
        comp_metric = f"{metric}_Comp"

        # Adicionar colunas ao DataFrame de comparação
        comparison_df[orig_metric] = df_orig_filtered[metric].round(3)
        comparison_df[comp_metric] = df_comp_filtered[metric].round(3)

    # Salvar o DataFrame no Excel
    with pd.ExcelWriter(output_path, engine="openpyxl", mode="a", if_sheet_exists="replace") as writer:
        comparison_df.to_excel(writer, sheet_name=sheet_name, index=False)

    # Aplicar formatação no Excel
    workbook = load_workbook(output_path)
    worksheet = workbook[sheet_name]

    # Definição de estilos
    equal_style = PatternFill(start_color="ADD8E6", end_color="ADD8E6", fill_type="solid")  # Azul claro
    worse_style = PatternFill(start_color="FF0000", end_color="FF0000", fill_type="solid")  # Vermelho
    better_style = Font(bold=True)  # Negrito

    for row in range(2, len(comparison_df) + 2):  # Começa na linha 2 para ignorar cabeçalhos
        for col_idx, metric in enumerate(metrics, start=1):
            orig_col = col_idx * 2  # Coluna do valor original
            view_col = orig_col + 1  # Coluna do valor da vista
            
            orig_value = worksheet.cell(row=row, column=orig_col).value
            view_value = worksheet.cell(row=row, column=view_col).value

            if isinstance(orig_value, (int, float)) and isinstance(view_value, (int, float)):
                if view_value > orig_value:
                    worksheet.cell(row=row, column=view_col).font = better_style
                elif view_value < orig_value:
                    worksheet.cell(row=row, column=view_col).fill = worse_style
                else:
                    worksheet.cell(row=row, column=view_col).fill = equal_style

    workbook.save(output_path)
    workbook.close()
    print(f"Planilha {sheet_name} formatada com sucesso: {output_path}")

In [13]:
# Carregar as abas da planilha
original_df = load_and_filter_sheet(excel_path, "Original")
equatorial_df = load_and_filter_sheet(excel_path, "Equatorial")
polar_df = load_and_filter_sheet(excel_path, "Polar")

/tmp/ipykernel_110538/2991480928.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_filtered[numeric_columns] = df_filtered[numeric_columns].astype(float)
/tmp/ipykernel_110538/2991480928.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_filtered[numeric_columns] = df_filtered[numeric_columns].astype(float)

In [15]:
original_df

    Unnamed: 0     Classes  Accuracy  Precision  Recall  F1-Score  Support
0            0  asphodelus     1.000      1.000   1.000     1.000     34.0
1            1  calicotome     0.993      0.980   0.993     0.986    298.0
2            2    castanea     1.000      1.000   1.000     1.000    218.0
3            3   ceratonia     0.940      0.931   0.940     0.935    100.0
4            4      ebenus     1.000      1.000   1.000     1.000     22.0
5            5       erica     1.000      0.989   1.000     0.994    181.0
6            6  eucalyptus     0.971      0.971   0.971     0.971    170.0
7            7      ferula     0.988      1.000   0.988     0.994     83.0
8            8      myrtus     1.000      0.997   1.000     0.998    786.0
9            9        olea     0.994      0.994   0.994     0.994    790.0
10          10    origanum     0.971      0.982   0.971     0.976    171.0
11          11      oxalis     0.993      0.993   0.993     0.993    139.0
12          12       pinus     1.000      1.000   1.000     1.000     29.0
13          13    pistacia     1.000      1.000   1.000     1.000     34.0
14          14      salvia     0.989      0.994   0.989     0.991    178.0
15          15    satureja     0.944      1.000   0.944     0.971     71.0
16          16     sinapis     0.990      0.990   0.990     0.990    197.0
17          17     thymbra     0.993      0.993   0.993     0.993    146.0
18          18     urginea     1.000      1.000   1.000     1.000    109.0
19          19       vitis     0.985      0.989   0.985     0.987    269.0

In [16]:
equatorial_df

    Unnamed: 0     Classes  Accuracy  Precision  Recall  F1-Score  Support
0            0  asphodelus     1.000      1.000   1.000     1.000      5.0
1            1  calicotome     0.909      0.769   0.909     0.833     11.0
2            2    castanea     1.000      1.000   1.000     1.000    218.0
3            3   ceratonia     0.948      0.938   0.948     0.943     96.0
4            4      ebenus     1.000      1.000   1.000     1.000     22.0
5            5       erica     1.000      0.667   1.000     0.800      2.0
6            6  eucalyptus     1.000      0.750   1.000     0.857      6.0
7            7      ferula     1.000      1.000   1.000     1.000     67.0
8            8      myrtus     1.000      1.000   1.000     1.000      2.0
9            9        olea     0.996      0.993   0.996     0.994    767.0
10          10    origanum     0.963      0.990   0.963     0.976    108.0
11          11      oxalis     1.000      1.000   1.000     1.000     14.0
13          13    pistacia     1.000      1.000   1.000     1.000     33.0
14          14      salvia     0.981      1.000   0.981     0.990    104.0
15          15    satureja     0.950      1.000   0.950     0.974     40.0
16          16     sinapis     0.990      0.990   0.990     0.990    196.0
17          17     thymbra     1.000      1.000   1.000     1.000     62.0
18          18     urginea     1.000      1.000   1.000     1.000    109.0
19          19       vitis     0.988      0.992   0.988     0.990    248.0

In [18]:
# Comparar Original x Equatorial
print("Comparação Original x Equatorial:")
comparison_oxe = compare_tables(original_df, equatorial_df)
print(comparison_oxe)

Comparação Original x Equatorial:
       Classes  Accuracy_Orig  Accuracy_Comp Accuracy_Comparison  \
0   asphodelus          1.000          1.000               Equal
1   calicotome          0.993          0.909               Worse
2     castanea          1.000          1.000               Equal
3    ceratonia          0.940          0.948              Better
4       ebenus          1.000          1.000               Equal
5        erica          1.000          1.000               Equal
6   eucalyptus          0.971          1.000              Better
7       ferula          0.988          1.000              Better
8       myrtus          1.000          1.000               Equal
9         olea          0.994          0.996              Better
10    origanum          0.971          0.963               Worse
11      oxalis          0.993          1.000              Better
13    pistacia          1.000          1.000               Equal
14      salvia          0.989          0.981               Worse
15    satureja          0.944          0.950              Better
16     sinapis          0.990          0.990               Equal
17     thymbra          0.993          1.000              Better
18     urginea          1.000          1.000               Equal
19       vitis          0.985          0.988              Better

    Precision_Orig  Precision_Comp Precision_Comparison  Recall_Orig  \
0            1.000           1.000                Equal        1.000
1            0.980           0.769                Worse        0.993
2            1.000           1.000                Equal        1.000
3            0.931           0.938               Better        0.940
4            1.000           1.000                Equal        1.000
5            0.989           0.667                Worse        1.000
6            0.971           0.750                Worse        0.971
7            1.000           1.000                Equal        0.988
8            0.997           1.000               Better        1.000
9            0.994           0.993                Worse        0.994
10           0.982           0.990               Better        0.971
11           0.993           1.000               Better        0.993
13           1.000           1.000                Equal        1.000
14           0.994           1.000               Better        0.989
15           1.000           1.000                Equal        0.944
16           0.990           0.990                Equal        0.990
17           0.993           1.000               Better        0.993
18           1.000           1.000                Equal        1.000
19           0.989           0.992               Better        0.985

    Recall_Comp Recall_Comparison  F1-Score_Orig  F1-Score_Comp  \
0         1.000             Equal          1.000          1.000
1         0.909             Worse          0.986          0.833
2         1.000             Equal          1.000          1.000
3         0.948            Better          0.935          0.943
4         1.000             Equal          1.000          1.000
5         1.000             Equal          0.994          0.800
6         1.000            Better          0.971          0.857
7         1.000            Better          0.994          1.000
8         1.000             Equal          0.998          1.000
9         0.996            Better          0.994          0.994
10        0.963             Worse          0.976          0.976
11        1.000            Better          0.993          1.000
13        1.000             Equal          1.000          1.000
14        0.981             Worse          0.991          0.990
15        0.950            Better          0.971          0.974
16        0.990             Equal          0.990          0.990
17        1.000            Better          0.993          1.000
18        1.000             Equal          1.000          1.000
19        0.988            Better          0.987          0.990

   F1-Score_Comparison
0                Equal
1                Worse
2                Equal
3               Better
4                Equal
5                Worse
6                Worse
7               Better
8               Better
9                Equal
10               Equal
11              Better
13               Equal
14               Worse
15              Better
16               Equal
17              Better
18               Equal
19              Better

In [19]:
with pd.ExcelWriter(excel_path, engine="openpyxl", mode="a", if_sheet_exists="replace") as writer:
    comparison_oxe.to_excel(writer, sheet_name="Original_vs_Equatorial", index=False)